In [5]:
#import libraries
from bs4 import BeautifulSoup
import requests
import smtplib
import time
import datetime

In [66]:
# connect to amazon
url = "https://www.amazon.ae/Analyst-Science-Actuary-Accountant-Programmer/dp/B0DJBTGT31/ref=sr_1_1?crid=26BLYMF7PF81G&dib=eyJ2IjoiMSJ9.NQVfUkpd1zzg-TKCy4k4UR8cTYh666NP2plvPsDmNpz9WPxzti4vQYVMgVjk9rxhRex6LNqfW8JJo_3u7GqvfyM7ay0CX8wbM6w0xD00XFCq3hd974Hh3RKXHauQuZ6Txla9h-4OAgVNKzF3I7DgM7eQCb2MkJeru0Zjx79P3zLP4PNpV1woq-Q8fX3icLfoIJaH9cIq7St6lIbRVp4gN5PNV2ckzD2a3lUYA8hFbuknwE0HcbsYJuLozylqdP5sVr34cHxeAsahAoyZCJ_T3QMYCobJQBN_PSZvZUGxBd4.Ybe2xFXxJQ5BlvTSdva3FXzNmE4Yi3l7dlZkXx3pSTU&dib_tag=se&keywords=data%2Banalyst%2Btshirt&qid=1792419268&sprefix=data%2Banalyst%2Btsh%2Caps%2C346&sr=8-1&ufe=app_do%3Aamzn1.fos.b4f74a7b-9d54-420b-9003-7e54957e6f89&th=1"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36 OPR/136.0.0.0 (Edition ms_store_gx)"}

page = requests.get(url, headers = headers)

soup1 = BeautifulSoup(page.content, "html.parser")

soup2 = BeautifulSoup(soup1.prettify(),"html.parser")

title = soup2.find(id = "productTitle").get_text()

price = soup2.find(id = "apex-pricetopay-accessibility-label").get_text()

seller = soup2.find(id = "sellerProfileTriggerId").get_text()

print(title)
print(price)
print(seller)

            Shirts Data Analyst Data Analyst Shirts Data Science Shirts Actuary Analyst Shirts Accountant Shirts Programmer Shirts Data Shirts -Sizes M


              AED 115.00


                             Peaceful Oasis

In [67]:
#cleaning the data that we scraped

price = price.strip()[4:]
title = title.strip()
seller = seller.strip()
print(title)
print(price)
print(seller)

Shirts Data Analyst Data Analyst Shirts Data Science Shirts Actuary Analyst Shirts Accountant Shirts Programmer Shirts Data Shirts -Sizes M
115.00
Peaceful Oasis

In [55]:
#recording when we collect the data
import datetime

today = datetime.date.today()
print(today)

2026-10-19

In [68]:
#putting all the data into the csv the first time, do not run after the first time as the data will be wiped out and a new row will be put

import csv

header = ['title','price','daterecorded','seller']
data = [title, price, today, seller]

#with open('amazonDataset.csv','w', newline = '', encoding = 'UTF8') as f:
    #writer = csv.writer(f)
    #writer.writerow(header)
    #writer.writerow(data)

In [69]:
#to view the data without opening the csv file directly

import pandas as pd

pd.read_csv('amazonDataset.csv')

,title,price,daterecorded,seller
0,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis

In [ ]:
#appending data to the csv

with open('amazonDataset.csv','a+', newline = '', encoding = 'UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(data)

In [76]:
#can use this to send a mail to us when the price lowers. the timing of the mail also depends on how long we set the time in the while loop

def send_mail():
    server = smtplib.SMTP_SSL('smtp.gmail.com',465)
    server.ehlo()
    #server.starttls()
    server.ehlo()
    server.login('ben710@outlook.com','xxxxxxxxxxxxxxxx')
    
    subject = "The Shirt you want is below AED115! Now is your chance to buy!"
    body = "Benji, This is the moment we have been waiting for. Now is your chance to pick up the shirt of your dreams. Don't mess it up! Link here: https://www.amazon.com/Funny-Data-Systems-Business-Analyst/dp/B07FNW9FGJ/ref=sr_1_3?dchild=1&keywords=data+analyst+tshirt&qid=1626655184&sr=8-3"
   
    msg = f"Subject: {subject}\n\n{body}"
    
    server.sendmail(
        'ben710@outlook.com',
        msg
     
    )

In [70]:
#making everything a function for us to use in an automation for as long as we want

def check_price():
    url = "https://www.amazon.ae/Analyst-Science-Actuary-Accountant-Programmer/dp/B0DJBTGT31/ref=sr_1_1?crid=26BLYMF7PF81G&dib=eyJ2IjoiMSJ9.NQVfUkpd1zzg-TKCy4k4UR8cTYh666NP2plvPsDmNpz9WPxzti4vQYVMgVjk9rxhRex6LNqfW8JJo_3u7GqvfyM7ay0CX8wbM6w0xD00XFCq3hd974Hh3RKXHauQuZ6Txla9h-4OAgVNKzF3I7DgM7eQCb2MkJeru0Zjx79P3zLP4PNpV1woq-Q8fX3icLfoIJaH9cIq7St6lIbRVp4gN5PNV2ckzD2a3lUYA8hFbuknwE0HcbsYJuLozylqdP5sVr34cHxeAsahAoyZCJ_T3QMYCobJQBN_PSZvZUGxBd4.Ybe2xFXxJQ5BlvTSdva3FXzNmE4Yi3l7dlZkXx3pSTU&dib_tag=se&keywords=data%2Banalyst%2Btshirt&qid=1792419268&sprefix=data%2Banalyst%2Btsh%2Caps%2C346&sr=8-1&ufe=app_do%3Aamzn1.fos.b4f74a7b-9d54-420b-9003-7e54957e6f89&th=1"
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36 OPR/136.0.0.0 (Edition ms_store_gx)"}
    
    page = requests.get(url, headers = headers)
    
    soup1 = BeautifulSoup(page.content, "html.parser")
    
    soup2 = BeautifulSoup(soup1.prettify(),"html.parser")
    
    title = soup2.find(id = "productTitle").get_text()
    
    price = soup2.find(id = "apex-pricetopay-accessibility-label").get_text()
    
    seller = soup2.find(id = "sellerProfileTriggerId").get_text()


    price = price.strip()[4:]
    title = title.strip()
    seller = seller.strip()

    import datetime
    
    today = datetime.date.today()
    

    import csv

    header = ['title','price','daterecorded','seller']
    data = [title, price, today, seller]

    with open('amazonDataset.csv','a+', newline = '', encoding = 'UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

    if (price<115):
        send_mail()

In [73]:
#the automation here depending on the time given in time.sleep(1) (seconds)
#the error shows as we interrupted the loop as there is no condition to come out of the loop
while (True):
    check_price()
    time.sleep(1)

KeyboardInterrupt:

In [74]:
import pandas as pd

pd.read_csv('amazonDataset.csv')

,title,price,daterecorded,seller
0,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
1,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
2,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
3,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
4,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
5,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
6,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
7,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
8,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
9,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis
10,Shirts Data Analyst Data Analyst Shirts Data S...,115.0,2026-10-19,Peaceful Oasis